# .golangci.yml

run:
  # Timeout for the execution, 10 minutes.
  timeout: 10m
  # Exit with status 1 if issues are found. Essential for CI.
  issues-exit-code: 1
  # Include test directories.
  tests: true

linters-settings:
  dupl:
    # Threshold for code duplication.
    threshold: 100
  gocyclo:
    # Cyclomatic complexity limit.
    min-complexity: 15
  errcheck:
    # Check for unchecked assignments to blank identifier.
    check-blank: true

linters:
  # Disable all linters by default and enable only the ones we want.
  disable-all: true
  enable:
    # Essential and best-practice linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck

    # Style and quality linters
    - dupl
    - gocyclo
    - goconst
    - gofmt
    - goimports
    - revive
    - wsl

issues:
  # Exclude some common issues in test files.
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen # Test functions can be long
        - gocyclo

# End of configuration