version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:16-alpine
    container_name: social_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: social_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Social Media API
  api:
    build: .
    container_name: social_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PG_URL: postgres://postgres:password@db:5432/social_db?sslmode=disable
      JWT_SECRET: your-jwt-secret-here
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_data: